site_name: INFN CMS Analysis Facility
theme:
  name: material 
  palette:
    primary: "Deep Blue"
    accent: "Light Blue"
  logo: logo.jpeg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: "README.md"
  - Introduction: "intro/intro.md"
  - How it works:
    - Components: "WIP.md"
    - Network: "WIP.md"
    - Data access: "WIP.md"
    - Security: "WIP.md"
  - Quick Start: 
    - For users: "tutorials/tutorials.md"
    # - For admins:
    #   - Requirements: "get-started/get-started.md"
    #   - Deployment:
    #     - Preparation:
    #       - Setup oidc-agent
    #       - Setup DODAS client
    #     - Using INFN facility
    #     - Standalone setup
  - Developer guide:
    - Requirements: "dev/dev.md"
  #- From Helm to DODAS template: "from-helm2tosca.md"
repo_name: "comp-dev-cms-ita/AnalysisFacility"
repo_url: "https://github.com/comp-dev-cms-ita/AnalysisFacility.git"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/comp-dev-cms-ita'

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true